/** Ibom FM: light-hearted, family-friendly Naija-pidgin commentary. Lines never repeat until the whole bag for that topic has been used. */
const BASE = {
  start: ['And we dey go! Seatbelt on, vibes on, na Ibom FM!', 'Engine don wake! Make we cook!', 'Green light! Uyo, make we show dem!', 'Na your turn now. The road dey wait!', 'Oya, show dem wetin Akwa Ibom boys and girls dey do!', 'Clutch dey sleep? No wahala, we go wake am!'],
  idle: ['You dey listen to Ibom FM, number one station for people wey dey road!', 'Traffic for Abak Road dey slow like Sunday service. Drive safe o!', 'Remember: na road we dey drift, no be market!', 'Uyo na clean city, dem talk. Pothole no dey inside that report!',
    'Na Ibom FM dey bring you jam after jam. No change that dial o!', 'Oga driver, hold that steering like say na your pension you carry!', 'Akwa Ibom, the land of promise! And the road, the land of wahala!', 'If hungry catch you, stop for afang soup. If speed catch you, enjoy am!',
    'Weather report: the road dey hot, the tyres dey sing. Make you no sleep!', 'Message from Ikot Ekpene: "Abeg drift slowly, my tomatoes dey the boot!"', 'Shout out to everybody for Itam market. Una dey try!', 'This one na for all danfo drivers: we see una, una no see us!',
    'Okada man just wave. Even him dey respect your skills!', 'We dey rock Uyo today! From Ibom Plaza to Itam, na vibes!', 'Fuel price fit rise, but your swagger no dey pay tax!', 'Ibom FM: where the beat dey enter your engine!', 'Your phone dey ring? Abeg ignore am. Road dey call you pass!',
    'One love to my people for Eket, Oron, Abak and Ikot Abasi!', 'Traffic warden don blow whistle but your own na music. Keep going!', 'Na Nigerian road be this: smooth for one minute, drama for the next!', 'Make you no forget: edikang ikong for lunch, drift for evening!',
    'Total vibes only! Wahala, abeg stay for village!', 'Na who dey lead? Na you o! Others dey follow, dey chop your dust!'],
  crash: ['Driver, na you get the road? Abeg look front!', 'Ouch! That one go reach Monday!', 'Chai! Mechanic don dey smile from afar!', 'Wetin do you? Your eye dey for head or na for pocket?', 'Gbam! Even the road feel that one!', 'Na so bumper dey fall for hand, oga!',
    'Haba! Na parking you dey look for?', 'That sound? Na your insurance dey cry!', 'Brake dey, you know? E dey the middle pedal o!', 'Ehen! New dent, new story. You no go lie to your papa!', 'Oya, shake body. Na only metal spoil!', 'Na so e be! Next time, try the empty lane!'],
  bigcrash: ['Chineke! Wetin be that?! Even Lagos traffic no dey do that one!', 'Ah ah ah! That crash fit show for Nollywood!', 'Oga!!! Hospital or panel beater first? E dey sweet o!', 'Wooooh! Neighbours for Ikot Ekpene don hear that one!', 'Kpa! Na landmark crash be that! Dem go name junction after you!', 'Jesus! Even the airbag dey shake hand!'],
  lastlife: ['Oga, na one life remain! Hold your steering like your pension!', 'Last chance! Even prayer point no fit save you now, drive well!', 'Four cars don feel your wahala. Na the fifth one go end am!', 'Abeg, no touch anybody again! Na only one more wey remain!', 'Red alert! One more hit and na so e go be!'],
  gameover: ['Na so e be! Panel beater go bless you this month!', 'Game over, my guy! Even police no fit settle that one!', 'Five cars? Na so we do am for Uyo? Take small break, come back strong!', 'Insurance don run go meet mama. Make we try again!', 'Na dust remain! But legends dey rise from dust, oya go again!'],
  revive: ['Ayy! Money talk, car don rise! Na so rich people dey do!', 'Resurrection! Even Lazarus dey clap for you!', 'Coins don work! Back for road, oga!', 'Mechanic say "e dey come", and e come! Back for action!', 'Na fresh paint and new heart! Oya, no waste am!'],
  nearmiss: ['Omo! Even okada man no fit pass that gap!', 'Razor-thin! Your guardian angel dey work overtime!', 'Ahh! Paint no even touch. Una dey try!', 'That one na needle for haystack! Wow!', 'Omo, you thread am! Tailor dey envy you!', 'Close shave! Barber dey ask for your number!',
    'Abeg slow down, the angels don tire!', 'Na so you go pass inside traffic like okada? Respect!', 'Another one gone like wind! Mirror no even see am!', 'Wetin be that? Even God, Him wipe forehead!'],
  streak: ['Near-miss after near-miss! You be ghost for road!', 'Chain of luck! Na who give you this blessing?', 'Na Ibom FM official Traffic Ninja be this!', 'Streak dey burn! Na so we like am!', 'Dem no go catch you! You dey thread through like needle!'],
  drift: ['Oga, you dey cook rice for road! Smoke everywhere!', 'Clean slide! Uyo no go shame you!', 'Tyre dey cry but we dey smile!', 'Na drift be that! Fast and Furious dey call you!', 'Smoke dey rise like chimney for Aba!', 'You turn road to ice rink! Fine boy!', 'Sideways Sunday! Your tyres go need prayer!', 'See as e dey slide like new soap for bathroom!'],
  perfect: ['PERFECT! Even judge dey stand up clap!', 'Machine! Na engineer drive that one!', 'Zero mistake! Na so we like am!', 'Clean like Sunday white! Omo!'],
  combo: ['Combo on fire! King of Uyo Streets dey come!', 'Chai! Na who teach you this one? Combo dey rise!', 'Combo dey stack like jollof for wedding!', 'Multiplier dey ginger! No stop now!', 'Na combo be this or na mathematics? Number dey climb!'],
  offroad: ['Oga, that na grass o, no be road!', 'You dey go village? Road dey this side!', 'Wetin dey for bush? Snake? Come back road!', 'GPS talk say: "Abeg return to the tarred road." Na the Ibom way!', 'Dust don cover everything! Car wash go cost you o!'],
  fast: ['Speedometer dey shake! Police go need helicopter!', 'You dey fly like Ibom Air! Just no land for pavement!', 'Chai! This speed na for aeroplane! Keep eye for road!', 'Top speed! The wind dey beg you to slow down!', 'Even lightning dey look you like "who be this one?"', 'Na rocket dey inside that engine?'],
  rain: ['Rain don start! Road slippery like new soap. Drive like say egg dey for boot!', 'Heavy rain for Uyo! Wiper go work overtime o!', 'Abeg careful, rain dey wash the road and your confidence!', 'God dey pour water for road, make you no pour speed for am!', 'Rain dey fall like say Uyo wan bath! Grip don reduce o!'],
  night: ['Night time for Uyo! Headlight on, vibes on!', 'Uyo for night na another level! The lights dey sing!', 'Midnight drive, no be thief o, na pure style!', 'Night owl dey road! Keep your eye open!'],
  pothole: ['Ah ah! That pothole don collect your suspension!', 'Pothole say hello! Government don promise fix am since 2005!', 'Boom! Another pothole certificate for your car!', 'Na pothole be that or crater? NASA go need to see am!', 'Pothole dey hold your tyre like long-lost relative!'],
  cone: ['Wetin cone do you? Construction people dey cry!', 'Cone don fly like Ibom Air! Hope e get landing permit!', 'Orange cone don go heaven! Our condolences!', 'Strike! Na bowling you dey play?', 'Oya, pick the cone make e no reach work tomorrow!'],
  flood: ['Flood! Na boat you dey drive now?', 'Water dey for road! Aquaplane championship, here we go!', 'Splash! Your car don take free wash!', 'Careful! Na swimming pool be that, no be road!'],
  km: ['Another kilometre down! Na marathon runner be you!', 'Distance dey climb! Road no get end today!', 'One more K! Your odometer dey smile!', 'Long road, longer legend. Keep going!', 'Na who dey count? Ibom FM dey count with you!'],
  lap: ['Another lap done! Uyo traffic warden dey salute!', 'Lap complete! The crowd dey roar!', 'Round and round like roundabout for Ibom Plaza!', 'Lap bonus! Money dey enter pocket!'],
} as const;
const MORE = {
  start: ['Seatbelt on? Good. Pride off? Even better. Oya go!', 'Ibom FM don dey live! Foot for ground, eye for road!', 'Na so we start am! Make e sweet like pawpaw!', 'All who dey Uyo, make una hear this engine: na champion dey road!', 'Green light don show! If your mama dey watch, make she proud!', 'Oya! No dey look back, na front dey pay!'],
  idle: ['Traffic warden for Ikot Ekpene say: "Who dey drive like say na Sunday?" Na you!', 'Reminder: afang soup no dey fit inside cup holder. Drive well!', 'This one na for the wonderful people for Eket. Una dey try o!', 'If you hear "chop and go" na food, no be traffic instruction!', 'Fuel station queue dey long, but your swagger no dey queue!', 'My guy, even GPS don give up on you. Na pure instinct!', 'Okada man don overtake me for this radio. Shame!', 'Weather report: sunshine for your front, wahala for your back!', 'Na the road be your teacher, and pothole be the strict headmaster!', 'Abeg, whoever dey sell roasted plantain for the junction, send me two!', 'Who dey pay for this fuel? Na your mama! Say thank you!', 'Danfo conductor shout: "Oshodi! Oshodi!" But we dey Uyo, my brother!', 'Make una no forget to greet your elders before una drift!', 'Naija no dey carry last! Even for traffic, we dey find shortcut!', 'Breaking news: Local driver discovers accelerator pedal. More at ten!', 'Make we pray for the road: Lord, let the tyres hold and the police look away!', 'Message from Oron: "My cousin say him fit drift. Make una prove am!"', 'Ibom FM sponsored by... nobody! We just dey vibe!', 'If sleep catch you, shake body. If speed catch you, shake more!', 'The only thing wey dey slow for Uyo na the generator wey no gree start!', 'NEPA don take light? No problem, your headlight dey shine!', 'Okay okay, who dey eat suya inside car? I smell am from here!', 'Pepper soup for evening, drift for morning. Na the Ibom lifestyle!', 'Una see that mama wey dey cross road like Usain Bolt? Respect!', 'Today fuel price don rise again. Your style no dey affected!', 'A friend tell me say road dey wide. I tell am: na your skill dey wide!', 'Any person wey dey sleep for back seat, wake up! Na history we dey make!', 'Na only for Akwa Ibom you go see car dey dance and road dey clap!', 'Make we hear from you, Ikot Abasi! Una dey hear us?', 'Mama put plenty pepper for your lunch? Then press the pedal gently!', 'Small small, we dey enter top gear. No rush, but rush small!', 'Even the tortoise dey look you like "who be this speedy person?"', 'Driving school certificate dey your pocket? If no, just pretend!', 'The road no be for lazy people. Na for champions like you!', 'Ibom Plaza, Ibom Icon, Ibom Air: the only three things wey dey fly here!', 'Make we greet traffic warden. He dey look like him never chop since morning!', 'Plan your life like Uyo roundabout: go round, round, come back!', 'Fine boy, fine girl, fine car: the road dey complete!', 'This song na to calm your engine. Your engine no gree calm!', 'Oga, you dey drive or you dey dance? Your car dey wiggle like owambe!'],
  crash: ['Who put that car there? Na wetin? Insurance dey ask!', 'Bam! Your bumper don say "goodbye, I dey go"!', 'Na money you dey carry or na wahala?', 'Ouch! Even the airbag dey wonder "I dey needed?"', 'Mechanic don text: "I get new boat, thanks!"', 'The horn dey sound, the car dey cry. Na so life be!', 'Gbosa! That one go sound for panel beater hotline!', 'Oga, na driving or na wrestling you dey do?', 'Big dent, bigger story. Mama go dey ask!', 'Your steering wheel say "I no be that one o!"', 'Ah ah! The other car even apologise!', 'Chai! Na the road hold your hand but you pull away!'],
  bigcrash: ['Kpuff! Smoke dey rise like that of suya stand!', 'Nollywood director don offer you a contract after that scene!', 'That crash don reach Lagos! Even Third Mainland Bridge dey shake!', 'Heavens! Mechanic don dey buy new house!', 'Na movie? Na reality? Na wahala, my brother!', 'Wooh! Even the ancestors dey go "ehn?"', 'The sound alone fit start generator! Wow!', 'Pastor! Pastor! We need prayer for this car!'],
  lastlife: ['One life remain! Treat am like last bottle of Fanta for party!', 'Ibom FM dey beg: no hit again, na your last chance!', 'Careful o! Last life dey sweet but e dey scary!', 'Even the gate-man for heaven dey say "abeg, wait small!"'],
  gameover: ['Na so e be! Next time make you drive like say egg dey for hand!', 'Oya, take water, dust the shame, and try again!', 'Five hits? You dey collect cars like Pokemon!', 'Game over! But your swagger no dey over!', 'Even Usain Bolt fit fall. Stand up, my guy!', 'The road say, "Come back tomorrow, I no dey vex!"'],
  revive: ['Fresh engine, fresh mind, same wahala! Oya go!', 'Naira don talk, and the car don listen!', 'Back from the dead! Even Nollywood no get that script!', 'Mechanic dey chop money but you dey chop road!', 'Rise and shine, my champion!'],
  nearmiss: ['Haba! Even mosquito no fit pass that gap!', 'You pass so close, the other driver don see the interior of your soul!', 'Wow! That one na millimetre magic!', 'Another one! The traffic dey beg you for mercy!', 'You thread that gap like Aba tailor!', 'The paint dey wonder how you escape!', 'Na magic or na luck? Whatever, na swagger!', 'If that gap get cashier, e go collect tax!', 'The other driver don bless himself three times!', 'Road dey shake but you dey calm!'],
  streak: ['You dey spin gap after gap like owambe DJ!', 'Na streak be this or you don sign pact with road?', 'Streak don long pass Uyo to Abak road!', 'Even Google Maps no fit predict your path!', 'Ibom FM Traffic Ninja of the Year! Na you!'],
  drift: ['Smoke, sound and style! Na combo be that!', 'You dey carve the road like Sunday rice!', 'Sideways like crab! Fine boy!', 'Tyre dey sing gospel, driver dey dance!', 'See slide! Even police dey take video!', 'You turn the road to dance floor! Owambe!', 'The car dey wave goodbye to straight line!', 'Drift level: Akwa Ibom professional!', 'Some people dey go straight, but you dey go sideways. Respect!', 'The tyres dey beg for mercy but na smoke you dey serve!', 'Burnt rubber smell sweet pass suya!', 'You and that corner, na love story!'],
  perfect: ['PERFECT! Even the road dey stand and clap!', 'Zero shaking! Na engineer you be!', 'That one sweet like fresh-cut pineapple!', 'Judges dey give you ten, ten, ten!', 'Clean slide! Na smooth like baby powder!'],
  combo: ['Combo dey climb like price of garri!', 'The multiplier don dey breathe fire!', 'Na who dey count? Calculator don faint!', 'Combo on top! Ibom FM dey scream!', 'This your combo go reach moon!', 'Your points dey multiply like rabbits!'],
  fast: ['Speed don pass sign post! Police no fit catch you!', 'You dey fly low! Ibom Air dey jealous!', 'The wind dey beg: "Abeg, slow down!"', 'Na jet engine dey your boot?', 'Even the lightning dey say "wait for me!"', 'Fast like Lagos landlord when rent fall due!', 'Your tyres don forget the ground!', 'Gone in sixty seconds? Na sixty milliseconds for you!'],
  rain: ['Rain dey fall, but your spirit dey dry!', 'Wet road, wet shoes, wet tyres, no problem!', 'Drive gentle o! Even duck no dey slip like this!', 'God dey water Uyo for free. Abeg don\'t waste am!', 'Wiper, work! Na your time!', 'Rainy season: the only time tomato price and potholes dey rise together!'],
  night: ['Night don fall, but your headlights dey shine like owambe!', 'Moon dey watch you from the sky. Make e proud!', 'Night driving: when only the brave and the data-less dey road!', 'Uyo after dark na another film!', 'Ghosts dey sleep, but you dey drive. Brave person!'],
  pothole: ['Pothole don collect your wheel like landlord collect rent!', 'Another one! Uyo roads dey dig for gold!', 'Boom! That one na natural speed bump!', 'Even the tyre dey cry "my mama!"', 'That pothole get tenant? Because e get address!', 'Pothole dey say hello. You dey say hello back with suspension!', 'The tyre don get new friend!', 'You find the only pothole for road? Talent!'],
  cone: ['Cone down! Construction people go cry tomorrow!', 'You don score goal! Orange cone, sorry o!', 'Strike! Bowling champion for Ibom!', 'That cone na the road manager. You just fire am!', 'The cone fly like it get Ibom Air ticket!', 'Orange confetti for the winner!'],
  flood: ['Splash! Car wash for free!', 'Is it road or river? Is it car or boat?', 'Water for road? Even Noah dey look!', 'You just make waves! Surfing champion!', 'Careful o! Fish dey look for apartment inside there!'],
  km: ['Another kilometre! Na NYSC walking, but with engine!', 'Odometer dey smile like politician for campaign!', 'You dey chop kilometre like pounded yam!', 'Kilometre don add, wahala don reduce!', 'Na road trip for the whole Akwa Ibom!', 'Long journey, short patience, big engine!'],
  lap: ['Lap done! Roundabout dey dizzy!', 'Another round! The crowd dey go crazy!', 'Na circle you dey draw? Clean!', 'Lap complete! Your mama dey cheer from the balcony!', 'Round, round, money, money!'],
  offroad: ['Grass dey for left, road dey for right. Abeg choose!', 'You dey go farm? Nobody dey wait you there!', 'The goat dey look you like "who be this person?"', 'Bush path na shortcut to wahala!', 'Return to tarred road! The tortoise dey laugh!', 'You don discover new road. Government go name am after you!'],
  pickup: ['Cha-ching! Naira dey enter pocket!', 'Money for road! Na who drop am?', 'Small small money dey add up! Na so billionaire start!', 'Pick am, pick am! Rich uncle dey proud!', 'Coin collected! Ibom FM dey bless you!', 'You dey collect coin like ATM!', 'Cash! Cash! Na so we love am!', 'That one go buy suya! Maybe two!', 'Fresh naira, no be counterfeit!', 'Money dey follow you like shadow!', 'Wallet don get fatter! Alhamdulillah, glory be to God!', 'Chop am before somebody else see am!', 'Coin! Coin! Even the bank manager dey clap!', 'The road dey pay you salary today!'],
  achievement: ['Achievement unlocked! Make we dey celebrate!', 'Ibom FM announce: new trophy for the champion!', 'Medal don land! Put am for sitting room!', 'Na award be this? Where my own?', 'You don level up! Politicians dey envy!', 'Trophy! Make una clap for this legend!', 'New achievement! Your mama go tell her friends!', 'Baba God, we thank you for this achievement!'],
  mplead: ['You dey front! Your friend dey chop your dust!', 'Lead dey your hand! Hold am like fresh egusi!', 'Na you dey show the way! Friend dey follow shadow!', 'Ahead! Your friend dey wonder wetin you chop!', 'Leader of the pack! Make the crowd clap!', 'Oga, no relax! Friend still dey behind you!', 'You dey lead! Make you no look back o!', 'The score dey your side! Keep am so!'],
  mptrail: ['Your friend dey ahead! Wake up o!', 'Behind? No wahala! Small drift go fix am!', 'Friend don pass you! Respond!', 'Abeg, no sleep! Score dey hotter for front!', 'You dey chase! Make the smoke dey follow!', 'Oya press am! Friend dey ahead like Lagos traffic!', 'The gap no big. Cook am!', 'Catch up, my person! Na only small gap!'],
  mpwin: ['You win! Your friend go dey hear am for one week!', 'Champion of the room! Tell am to buy you suya!', 'Victory! Drum dey beat! Dancing! Dancing!', 'Winner winner jollof dinner!', 'Bragging rights unlocked! Use am wisely!', 'The trophy dey sleep for your side today!'],
  mplose: ['E no easy! Rematch go sweet!', 'You lose small, but your spirit dey strong!', 'Abeg shake hand and run am back!', 'Friend win today, but tomorrow na another day!', 'Close one! Make we cook am again!', 'Defeat dey teach better than victory! Ask my uncle!'],
  bus: ['Danfo don stop for middle of road! Normal!', 'That bus fit carry whole village! Careful o!', 'Conductor dey shout: "Driver, no touch!"', 'Yellow bus: the king of Nigerian road!', 'Bus ahead! Even police dey give way!'],
} as const;
const merged: Record<string, string[]> = {};
for (const k of new Set([...Object.keys(BASE), ...Object.keys(MORE)])) merged[k] = [...((BASE as any)[k] ?? []), ...((MORE as any)[k] ?? [])];
export type RadioKind = keyof typeof BASE | keyof typeof MORE;
export const LINES = merged as Record<RadioKind, string[]>;
const URGENT = new Set<RadioKind>(['bigcrash', 'lastlife', 'gameover', 'revive', 'start', 'achievement', 'mpwin', 'mplose']);

export class Radio {
  private t = 14; private cool = 0; private bag = new Map<RadioKind, string[]>();
  constructor(private out: (line: string) => void) {}
  tick(dt: number) { this.cool -= dt; this.t -= dt; if (this.t <= 0) { this.t = 20 + Math.random() * 12; this.say('idle'); } }
  private next(kind: RadioKind) { let b = this.bag.get(kind); if (!b || !b.length) { b = [...LINES[kind]]; for (let i = b.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [b[i], b[j]] = [b[j], b[i]]; } this.bag.set(kind, b); } return b.pop()!; }
  /** urgent lines (big crash, game over...) may cut in during the normal 7 s gap. */
  say(kind: RadioKind, urgent = URGENT.has(kind)) { if (this.cool > 0 && !urgent) return; if (this.cool > 4.5 && urgent) return; this.cool = urgent ? 6 : 7; this.out(this.next(kind)); }
}

let voice: SpeechSynthesisVoice | null | undefined;
/** Speaks a line with a Nigerian English voice when the device has one (falls back to any English voice). */
export function speak(line: string, volume = .65) {
  if (typeof speechSynthesis === 'undefined' || volume <= 0) return;
  if (voice === undefined) { const vs = speechSynthesis.getVoices(); if (vs.length) voice = vs.find(v => /en[-_]NG/i.test(v.lang)) ?? vs.find(v => /en[-_](GB|ZA|IN)/i.test(v.lang)) ?? vs.find(v => /^en/i.test(v.lang)) ?? null; }
  speechSynthesis.cancel(); const u = new SpeechSynthesisUtterance(line); if (voice) u.voice = voice; u.lang = voice?.lang ?? 'en-NG'; u.volume = Math.min(1, volume); u.rate = 1.08; u.pitch = .92; speechSynthesis.speak(u);
}
if (typeof speechSynthesis !== 'undefined') speechSynthesis.onvoiceschanged = () => { voice = undefined; };
